blueprint:
  name: "🎙️ Alexa: Script Pulizia Stanze Dreame"
  description: |
    ## 🚀 Cosa fa questo blueprint
    Crea uno **script personalizzato** per comandare il tuo robot Dreame con la voce tramite Alexa!
    
    ✅ **Pulizia mirata** di una stanza specifica  
    ✅ **4 modalità** di pulizia disponibili  
    ✅ **Pronto per Alexa** - nessuna configurazione aggiuntiva  
    ✅ **Facilmente clonabile** per multiple stanze  
    
    ## 🏠 Modalità di Pulizia Disponibili
    
    | Modalità | Descrizione | Tecnologia |
    |----------|-------------|------------|
    | 🧹 **Aspirazione** | Solo aspirazione | Cleaning Mode |
    | 💧 **Lavaggio** | Solo lavaggio | Cleaning Mode |
    | ✨ **Pulizia** | Aspirazione + Lavaggio | CleanGenius |
    | 🔥 **Pulizia Profonda** | Aspirazione + Lavaggio Intensivo | CleanGenius Deep |
    
    ## 📋 Prerequisiti
    1. ✅ Robot Dreame configurato in Home Assistant
    2. ✅ Helper delle stanze creato (usa il blueprint "🏠 Creazione Helper Stanze")
    3. ✅ Alexa configurata (Nabu Casa, Lambda, o Matter)
    
    ## 🎯 Come Usarlo
    
    ### Passo 1: Configura lo Script
    1. **Seleziona** il tuo robot e le entità necessarie
    2. **Inserisci** l'ID della stanza (trovalo nell'helper delle stanze)
    3. **Scegli** la modalità di pulizia
    4. **Salva** lo script con un nome descrittivo
    
    ### Passo 2: Esponi ad Alexa
    - **Nabu Casa**: Lo script apparirà automaticamente
    - **Matter**: Aggiungi il label "matter" allo script
    - **Lambda**: Configura nel tuo setup AWS
    
    ### Passo 3: Comandi Vocali
    **"Alexa, avvia [nome dello script]"**  
    **"Alexa, apri [nome dello script]"**
    
    ## 💡 Esempi Pratici
    
    ### Scenario: Pulizia del Bagno
    1. **Crea** script: "Aspirazione Bagno" (ID stanza: 5, modalità: Aspirazione)
    2. **Clona** script: "Pulizia Bagno" (stesso ID, modalità: Pulizia)
    3. **Comandi**: 
       - "Alexa, avvia aspirazione bagno" 
       - "Alexa, avvia pulizia bagno"
    
    ### Scenario: Cucina Completa
    - Script 1: "Pulizia Cucina" → "Alexa, avvia pulizia cucina"
    - Script 2: "Pulizia Profonda Cucina" → "Alexa, avvia pulizia profonda cucina"
    
    ## ⚙️ Note Tecniche
    - **CleanGenius**: Modalità avanzata che combina aspirazione e lavaggio
    - **Cleaning Mode**: Modalità base per aspirazione o lavaggio separati
    - **Timeout**: 10 secondi per il cambio delle impostazioni
    - **Validazione**: Controlla automaticamente che l'ID stanza sia valido
    
  domain: script
  source_url: https://raw.githubusercontent.com/Magnum9O/HA_BluePrints/main/Dreame/ITA/2_EsponiAdAlexa.yaml

  input:
    vacuum_entity:
      name: "🤖 Robot Dreame"
      description: |
        Seleziona il tuo aspirapolvere robot Dreame.
        
        💡 **Esempio**: `vacuum.dreame_l10s_ultra` o `vacuum.xiaomi_vacuum_cleaner`
      selector:
        entity:
          domain: vacuum

    cleangenius_select:
      name: "✨ Entità CleanGenius"
      description: |
        Seleziona l'entità che controlla la modalità **CleanGenius** del tuo robot.
        
        💡 **Come trovarla**: Cerca tra le entità `select` del tuo robot, di solito ha un nome come:
        - `select.nome_robot_cleangenius`
        - `select.dreame_cleangenius`
      selector:
        entity:
          domain: select

    cleaning_mode_select:
      name: "🔧 Entità Cleaning Mode"
      description: |
        Seleziona l'entità che controlla il **Cleaning Mode** (aspirazione/lavaggio separati).
        
        💡 **Come trovarla**: Cerca tra le entità `select` del tuo robot, di solito:
        - `select.nome_robot_cleaning_mode`
        - `select.dreame_cleaning_mode`
      selector:
        entity:
          domain: select

    room_id:
      name: "🏠 ID Stanza"
      description: |
        **Inserisci l'ID numerico** della stanza che vuoi pulire.
        
        🔍 **Come trovarlo**: 
        1. Usa il blueprint "🏠 Creazione Helper Stanze"
        2. Controlla l'helper creato per vedere "Nome Stanza (**ID**)"
        3. Inserisci solo il numero tra parentesi
        
        📝 **Esempio**: Se vedi "Cucina (3)", inserisci **3**
      selector:
        number:
          min: 0
          max: 999
          mode: box
      default: 0

    cleaning_preset:
      name: "🎯 Modalità di Pulizia"
      description: |
        Scegli la modalità di pulizia desiderata:
        
        🧹 **Aspirazione**: Solo aspirazione (CleanGenius OFF)
        💧 **Lavaggio**: Solo lavaggio (CleanGenius OFF)  
        ✨ **Pulizia**: Aspirazione + Lavaggio simultanei
        🔥 **Pulizia Profonda**: Aspirazione + Lavaggio intensivo
      selector:
        select:
          options:
            - label: "🧹 Aspirazione"
              value: "Aspirazione"
            - label: "💧 Lavaggio" 
              value: "Lavaggio"
            - label: "✨ Pulizia"
              value: "Pulizia"
            - label: "🔥 Pulizia Profonda"
              value: "Pulizia profonda"
      default: "Pulizia"

icon: mdi:robot-vacuum

mode: single

sequence:
  - variables:
      _vac: !input vacuum_entity
      _cg_sel: !input cleangenius_select
      _cm_sel: !input cleaning_mode_select
      _rid: !input room_id
      _preset_raw: !input cleaning_preset
      preset: "{{ (_preset_raw or 'Pulizia') | lower }}"

  # Validazione ID stanza
  - condition: template
    value_template: "{{ (_rid | int(default=-1)) >= 0 }}"
    alias: "Verifica validità ID stanza"

  # Branch in base al preset
  - choose:
      # PULIZIA PROFONDA → CleanGenius deep_cleaning
      - conditions:
          - condition: template
            value_template: "{{ preset == 'pulizia profonda' }}"
        sequence:
          - alias: "Imposta CleanGenius Deep Cleaning"
            service: select.select_option
            target:
              entity_id: "{{ _cg_sel }}"
            data:
              option: deep_cleaning

          - alias: "Attendi cambio modalità CleanGenius"
            wait_template: >-
              {{ states(_cg_sel) in ['deep_cleaning','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Avvia pulizia profonda stanza"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

      # PULIZIA (standard) → CleanGenius lasciato com'è (nessun cambio), poi avvio
      - conditions:
          - condition: template
            value_template: "{{ preset == 'pulizia' }}"
        sequence:
          - alias: "Avvia pulizia standard stanza"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

      # ASPIRAZIONE → CleanGenius OFF → cleaning_mode sweeping → avvio
      - conditions:
          - condition: template
            value_template: "{{ preset == 'aspirazione' }}"
        sequence:
          - alias: "Disattiva CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cg_sel }}"
            data:
              option: 'off'

          - alias: "Attendi disattivazione CleanGenius"
            wait_template: >-
              {{ states(_cg_sel) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Imposta modalità aspirazione"
            service: select.select_option
            target:
              entity_id: "{{ _cm_sel }}"
            data:
              option: sweeping

          - delay: "00:00:01"

          - alias: "Avvia aspirazione stanza"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

      # LAVAGGIO → CleanGenius OFF → cleaning_mode mopping → avvio
      - conditions:
          - condition: template
            value_template: "{{ preset == 'lavaggio' }}"
        sequence:
          - alias: "Disattiva CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cg_sel }}"
            data:
              option: 'off'

          - alias: "Attendi disattivazione CleanGenius"
            wait_template: >-
              {{ states(_cg_sel) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Imposta modalità lavaggio"
            service: select.select_option
            target:
              entity_id: "{{ _cm_sel }}"
            data:
              option: mopping

          - delay: "00:00:01"

          - alias: "Avvia lavaggio stanza"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ _rid | int }}"

    default: []