blueprint:
  name: Pulizia programmata Dreame (Semplice o Avanzata, con CleanGenius e Presenza)
  description: >
    Pianifica pulizie Dreame per mattina/sera (modalità semplice) o con
    fino a 4 blocchi indipendenti (modalità avanzata). Supporta selezione
    stanze per ID o nome (se fornisci la mappa), CleanGenius opzionale,
    controllo presenza opzionale e reset del flag "pulito oggi".

  domain: automation
  source_url: https://github.com/Magnum9O/HA_BluePrints/blob/main/Dreame/ScheduledCleaningAdvanced.yaml

  input:
    presence_helper:
      name: Helper presenza (opzionale)
      description: >
        Entità da confrontare (counter, input_boolean, input_select, ecc.).
        Se vuoto, la presenza è ignorata.
      default: ""
      selector:
        entity: {}

    presence_required_value:
      name: Valore presenza richiesto (opzionale)
      description: >
        Esempi: 1, home, on. Se vuoto e "Helper presenza" è valorizzato,
        la condizione presenza viene saltata.
      default: ""
