blueprint:
  name: "Dreame: Aggiorna elenco stanze"
  description: |
    Questo blueprint crea uno script che legge l'attributo ``rooms`` della mappa
    tasshack e aggiorna un helper `input_select` con l'elenco dei nomi delle stanze.

    Prima di utilizzare questo blueprint devi creare manualmente un helper
    `input_select` tramite l'interfaccia di Home Assistant (Impostazioni → Dispositivi
    e servizi → Helper → Aggiungi → Input Select). Lascia l'elenco delle opzioni
    vuoto. Seleziona poi quell'helper tra i campi di input di questo blueprint.

    Una volta eseguito lo script creato dal blueprint, l'`input_select` conterrà
    tutte le stanze rilevate sulla mappa. Potrai quindi utilizzarlo in altri
    blueprint o automazioni per scegliere una stanza senza dover digitare il nome.
  domain: script
  source_url: https://raw.githubusercontent.com/Magnum9O/HA_BluePrints/main/blueprints/BP_Dreame_Automation/dreame_update_rooms.yaml
  input:
    map_camera:
      name: "Mappa del robot"
      description: "Seleziona la camera tasshack che contiene l'attributo 'rooms'."
      selector:
        entity:
          domain: camera
    select_entity:
      name: "Input Select per le stanze"
      description: "Seleziona l'helper input_select da aggiornare con i nomi delle stanze."
      selector:
        entity:
          domain: input_select

sequence:
  # Estrarre la lista dei nomi delle stanze dall'attributo rooms
  - variables:
      # Copia le entità di input in variabili locali per evitare errori di Jinja quando gli input non sono definiti
      map_ent: !input map_camera
      select_ent: !input select_entity
      room_names: >-
        {% set names = [] %}
        {% set rooms = state_attr(map_ent, 'rooms') %}
        {% if rooms is mapping %}
          {% for key, val in rooms.items() %}
            {% set names = names + [val.name] %}
          {% endfor %}
        {% endif %}
        {{ names }}
  # Aggiornare l'input_select con la nuova lista
  - choose:
      # Se c'è almeno una stanza, aggiorna l'input_select con la lista
      - conditions:
          - condition: template
            value_template: "{{ room_names | length > 0 }}"
        sequence:
          - service: input_select.set_options
            data:
              entity_id: "{{ select_ent }}"
              options: >-
                {{ room_names }}
      # Altrimenti, notifica che non sono state trovate stanze
      - conditions: []
        sequence:
          - service: persistent_notification.create
            data:
              title: "Aggiornamento stanze"
              message: >-
                Non sono state trovate stanze nell'attributo 'rooms' della mappa {{ map_ent }}.
                Assicurati che l'integrazione tasshack abbia creato la mappa e che il robot abbia
                generato un layout con le stanze.
