blueprint:
  name: Espone script per Alexa
  description: |
    Crea uno script eseguibile da Alexa per avviare la pulizia di una stanza del robot Dreame.
    Integra CleanGenius per i preset "Pulizia" (standard) e "Pulizia profonda" (deep).

    Requisiti:
    - Integrazione Dreame funzionante.
    - Vacuum Map card (tasshack) che popola un input_select con opzioni tipo "Nome (ID)".
    - Un input_select (già popolato dal blueprint 1) contenente le stanze in formato "Nome (ID)".

    Alexa: dire "avvia <nome script>" oppure "apri <nome script>".

  domain: script

  input:
    vacuum_entity:
      name: Entità robot Dreame
      selector:
        entity:
          domain: vacuum

    room_helper:
      name: Helper stanze (input_select)
      description: Seleziona l'input_select già popolato con le stanze "Nome (ID)".
      selector:
        entity:
          domain: input_select

    cleaning_preset:
      name: Tipo di pulizia
      selector:
        select:
          options:
            - Aspirazione
            - Lavaggio con moci/rullo
            - Pulizia (Clean Genius)
            - Pulizia profonda (Clean Genius)
          multiple: false
          mode: dropdown

    use_clean_genius:
      name: Usa CleanGenius per i preset "Pulizia"
      description: Se attivo, Pulizia usa cleaning_mode 2 e Pulizia profonda usa cleaning_mode 3.
      default: true
      selector:
        boolean: {}

    suction_level:
      name: Livello aspirazione (opzionale)
      description: Se impostato, sovrascrive il livello (1-4).
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider

    water_volume:
      name: Livello acqua (opzionale)
      description: Se impostato, sovrascrive il livello (1-3).
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

    cleaning_passes:
      name: Passate (opzionale)
      description: Numero di passate (1-3).
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

mode: restart
icon: mdi:robot-vacuum

sequence:
  - variables:
      _helper: !input room_helper
      _vac: !input vacuum_entity
      _preset: !input cleaning_preset
      _use_cg: !input use_clean_genius
      _suction: !input suction_level
      _water: !input water_volume
      _passes: !input cleaning_passes

      room_label: "{{ states(_helper) | string }}"
      room_id: >-
        {% set s = room_label %}
        {% if '(' in s and ')' in s %}
          {{ s.split('(')[-1].split(')')[0] | int }}
        {% else %}
          {{ -1 }}
        {% endif %}

      preset_lc: "{{ (_preset or 'Pulizia') | lower }}"

      cleaning_mode: >-
        {% if _use_cg %}
          {% if preset_lc == 'pulizia' %}2
          {% elif preset_lc == 'pulizia profonda' %}3
          {% else %}{{ none }}
          {% endif %}
        {% else %}
          {{ none }}
        {% endif %}

  - condition: template
    value_template: "{{ room_id | int(-1) >= 0 }}"

  - service: dreame_vacuum.vacuum_clean_segment
    target:
      entity_id: "{{ _vac }}"
    data:
      segments:
        - "{{ room_id | int }}"
      suction_level: "{{ _suction if _suction is number else none }}"
      water_volume: "{{ _water if _water is number else none }}"
      cleaning_times: "{{ _passes if _passes is number else none }}"
      cleaning_mode: "{{ cleaning_mode if cleaning_mode is number else none }}"
