blueprint:
  name: Espone script per Alexa (Dreame + Vacuum Map, per stanza)
  description: |
    Crea uno script eseguibile da Alexa per avviare la pulizia di una stanza del robot Dreame.
    Usa CleanGenius per i preset "Pulizia" (standard) e "Pulizia profonda" (deep).
    Nessun livello aspirazione/acqua/passate: si usano i default del robot.

    Requisiti:
    - Integrazione Dreame funzionante.
    - Vacuum Map card (tasshack) che popola un input_select con opzioni tipo "Nome (ID)".
    - Un input_select (già popolato dal blueprint 1) contenente le stanze in formato "Nome (ID)".

    Alexa: dire "avvia <nome script>" oppure "apri <nome script>".

  domain: script

  input:
    vacuum_entity:
      name: Entità robot Dreame
      selector:
        entity:
          domain: vacuum

    room_helper:
      name: Helper stanze (input_select)
      description: Seleziona l'input_select già popolato con le stanze "Nome (ID)".
      selector:
        entity:
          domain: input_select

    cleaning_preset:
      name: Tipo di pulizia
      selector:
        select:
          options:
            - Sola Aspirazione
            - Solo Lavaggio
            - Pulizia (Clean Genius)
            - Pulizia profonda (Clean Genius)
          multiple: false
          mode: dropdown

    use_clean_genius:
      name: Usa CleanGenius per i preset "Pulizia"
      description: Se attivo, Pulizia usa cleaning_mode 2 e Pulizia profonda usa cleaning_mode 3.
      default: true
      selector:
        boolean: {}

mode: restart
icon: mdi:robot-vacuum

sequence:
  - variables:
      _helper: !input room_helper
      _vac: !input vacuum_entity
      _preset: !input cleaning_preset
      _use_cg: !input use_clean_genius

      room_label: "{{ states(_helper) | string }}"
      room_id: "{{ iif('(' in room_label and ')' in room_label, room_label.split('(')[-1].split(')')[0] | int, -1) }}"
      preset_lc: "{{ (_preset or 'Pulizia') | lower }}"

      # CleanGenius: 2 standard (Pulizia), 3 deep (Pulizia profonda); altrimenti non impostare
      cleaning_mode: "{{ 2 if (_use_cg and preset_lc == 'pulizia') else (3 if (_use_cg and preset_lc == 'pulizia profonda') else omit) }}"

  - condition: template
    value_template: "{{ room_id | int(-1) >= 0 }}"

  - service: dreame_vacuum.vacuum_clean_segment
    target:
      entity_id: "{{ _vac }}"
    data:
      segments:
        - "{{ room_id | int }}"
      cleaning_mode: "{{ cleaning_mode }}"
