blueprint:
  name: Dreame · Script Alexa (da index stanze) — minimal
  description: >
    Avvia la pulizia di una stanza del Dreame leggendo l'ID segmento
    dall'helper `input_select` popolato dal Blueprint Index Stanze.
    Uso: seleziona la stanza nell'helper (formato "Nome (ID)") e lancia lo script.
    
  domain: script

  input:
    select_entity:
      name: Helper index stanze ("Nome (ID)")
      description: L'input_select popolato dal BP#1 (voci come "Cucina (3)")
      selector:
        entity:
          domain: input_select

    vacuum_entity:
      name: Entità aspirapolvere (vacuum.*)
      selector:
        entity:
          domain: vacuum

    # Parametri opzionali (applicati solo se supportati dal modello)
    cleaning_profile:
      name: Tipo di pulizia (solo etichetta informativa)
      default: aspirazione
      selector:
        select:
          options:
            - aspirazione
            - lavaggio
            - pulizia
            - pulizia profonda

    suction_level:
      name: Livello aspirazione (opzionale)
      description: 1..4 se supportato. Vuoto = non cambiare
      default:
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider

    water_volume:
      name: Quantità acqua (opzionale)
      description: 1..3 se supportato. Vuoto = non cambiare
      default:
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

    cleaning_passes:
      name: Numero passate (opzionale)
      description: 1..3 se supportato. Vuoto = non cambiare
      default:
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

mode: single

sequence:
  - variables:
      select_ent: !input select_entity
      vac: !input vacuum_entity
      s_level: !input suction_level
      w_vol: !input water_volume
      passes: !input cleaning_passes

  # Parametri opzionali: applica solo se forniti
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ s_level is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_set_fan_speed
            data:
              entity_id: "{{ vac }}"
              speed_level: "{{ s_level | int }}"
      - conditions:
          - condition: template
            value_template: "{{ w_vol is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_set_water_volume
            data:
              entity_id: "{{ vac }}"
              volume: "{{ w_vol | int }}"
      - conditions:
          - condition: template
            value_template: "{{ passes is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_set_cleaning_passes
            data:
              entity_id: "{{ vac }}"
              passes: "{{ passes | int }}"

  # Leggi etichetta dall'helper e ricava l'ID segmento
  - variables:
      selected_label: "{{ states(select_ent) | default('') }}"
      segment_id: >-
        {% set opt = selected_label | trim %}
        {% if '(' in opt and ')' in opt %}
          {{ opt.split('(')[-1].split(')')[0] | int }}
        {% else %}
          {{ opt | int(default=-1) }}
        {% endif %}

  # Avvia pulizia solo se l'ID è valido
  - condition: template
    value_template: "{{ segment_id | int(-1) >= 0 }}"

  - service: dreame_vacuum.vacuum_clean_segment
    data:
      entity_id: "{{ vac }}"
      segments: ["{{ segment_id | int }}"]
