blueprint: ExposeToAlexa
  name: Espone gli script di pulizia ad Alexa
  description: >
    Crea uno script Alexa per pulire una stanza Dreame.
    - Se imposti **Segment ID fisso (override)**, lo script userà sempre quell'ID (consigliato per Alexa).
    - Se lo lasci vuoto, leggerà l'ID dall'helper `input_select` popolato dal Blueprint Index Stanze (BP#1).
    Se usi matter: Imposta subito un label agli script che crei in modo da esporli ad Alexa!

  domain: script

  input:
    select_entity:
      name: Helper index stanze ("Nome (ID)")
      description: L'input_select popolato dal BP#1 (voci come "Cucina (3)"). Usato solo se l'override è vuoto.
      selector:
        entity:
          domain: input_select

    vacuum_entity:
      name: Entità aspirapolvere (vacuum.*)
      selector:
        entity:
          domain: vacuum

    segment_id_override:
      name: Segment ID fisso (override)
      description: >
        Inserisci l'ID numerico della stanza (es. "3" per "Cucina (3)") che puoi ricavare dall'helper creato con il BP#1. 
        Attenzione: lascianod questo valore vuoto, lo script avvierà sempre la pulizia della stanza indiciata dall'helper!
        Per creare uno script indipendente dall'helper, questo campo va riempito con l'ID della stanza corrispondente
      default:
      selector:
        number:
          min: 0
          max: 9999
          step: 1
          mode: box

    # Opzionali: applicati solo se supportati dal modello
    cleaning_profile:
      name: Tipo di pulizia (etichetta informativa)
      default: aspirazione
      selector:
        select:
          options:
            - Sola Aspirazione
            - Solo Lavaggio con moci/rullo
            - Pulizia (Clean Genius)
            - Pulizia profonda (Clean Genius)

    suction_level:
      name: Livello aspirazione (opzionale)
      description: 1..4 se supportato. Vuoto = non cambiare
      default:
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider

    water_volume:
      name: Quantità acqua (opzionale)
      description: 1..3 se supportato. Vuoto = non cambiare
      default:
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

    cleaning_passes:
      name: Numero passate (opzionale)
      description: 1..3 se supportato. Vuoto = non cambiare
      default:
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

mode: single

sequence:
  - variables:
      select_ent: !input select_entity
      vac: !input vacuum_entity
      seg_override: !input segment_id_override
      s_level: !input suction_level
      w_vol: !input water_volume
      passes: !input cleaning_passes

  # Parametri opzionali: applica solo se forniti
  - choose:
      - conditions: "{{ s_level is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_set_fan_speed
            data:
              entity_id: "{{ vac }}"
              speed_level: "{{ s_level | int }}"
      - conditions: "{{ w_vol is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_set_water_volume
            data:
              entity_id: "{{ vac }}"
              volume: "{{ w_vol | int }}"
      - conditions: "{{ passes is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_set_cleaning_passes
            data:
              entity_id: "{{ vac }}"
              passes: "{{ passes | int }}"

  # Determina il segment_id finale: prima l'override, altrimenti derivato dall'helper
  - variables:
      segment_id: >-
        {% if seg_override is number %}
          {{ seg_override | int }}
        {% else %}
          {% set opt = (states(select_ent) | default('')) | trim %}
          {% if '(' in opt and ')' in opt %}
            {{ opt.split('(')[-1].split(')')[0] | int }}
          {% else %}
            {{ opt | int(default=-1) }}
          {% endif %}
        {% endif %}

  # Avvia pulizia solo se l'ID è valido
  - condition: template
    value_template: "{{ segment_id | int(-1) >= 0 }}"

  - service: dreame_vacuum.vacuum_clean_segment
    data:
      entity_id: "{{ vac }}"
      segments: ["{{ segment_id | int }}"]
