blueprint:
  name: Espone gli script di pulizia a Alexa (Dreame + Vacuum Map)
  description: |
    Crea uno script eseguibile da Alexa per avviare la pulizia di una stanza direttamente da Alexa.
    Requisiti:
    - Integrazione Dreame.
    - Vacuum Map card (tasshack) per l’helper con opzioni tipo "Nome (ID)".
    - Un input_select (già popolato dal primo blueprint) con le stanze in formato "Nome (ID)".
    Uso con Alexa: dire "avvia <nome script>" oppure "apri <nome script>".

  domain: script

  input:
    vacuum_entity:
      name: Entità robot Dreame
      description: Seleziona l'entità del robot aspirapolvere Dreame.
      selector:
        entity:
          domain: vacuum

    room_helper:
      name: Helper stanze (input_select)
      description: >
        Seleziona l'input_select già popolato con le stanze in formato "Nome (ID)".
      selector:
        entity:
          domain: input_select

    suction_level:
      name: Livello aspirazione (opzionale)
      description: Lascia vuoto per usare il valore predefinito del robot.
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider

    water_volume:
      name: Livello acqua (opzionale)
      description: Lascia vuoto per usare il valore predefinito del robot (solo modelli che lavano).
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

    cleaning_passes:
      name: Passate (opzionale)
      description: Numero di passate su stanza. Lascia vuoto per default.
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

mode: restart
icon: mdi:robot-vacuum

sequence:
  - variables:
      _helper: !input room_helper
      _vac: !input vacuum_entity
      _suction: !input suction_level
      _water: !input water_volume
      _passes: !input cleaning_passes

      # Testo selezionato nell'input_select, es. "Kitchen (3)"
      room_label: "{{ states(_helper) | string }}"
      # Estrai ID (tra parentesi)
      room_id: >-
        {% set s = room_label %}
        {% if '(' in s and ')' in s %}
          {{ s.split('(')[-1].split(')')[0] | int }}
        {% else %}
          {{ -1 }}
        {% endif %}

  # Verifica che l'ID sia valido
  - condition: template
    value_template: "{{ room_id | int(-1) >= 0 }}"

  # Applica opzionali se presenti
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ _suction is number and _water is number and _passes is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ room_id | int }}"
              suction_level: "{{ _suction | int }}"
              water_volume: "{{ _water | int }}"
              cleaning_times: "{{ _passes | int }}"

      - conditions:
          - condition: template
            value_template: "{{ _suction is number and _passes is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ room_id | int }}"
              suction_level: "{{ _suction | int }}"
              cleaning_times: "{{ _passes | int }}"

      - conditions:
          - condition: template
            value_template: "{{ _water is number and _passes is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ room_id | int }}"
              water_volume: "{{ _water | int }}"
              cleaning_times: "{{ _passes | int }}"

      - conditions:
          - condition: template
            value_template: "{{ _passes is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ room_id | int }}"
              cleaning_times: "{{ _passes | int }}"

      - conditions:
          - condition: template
            value_template: "{{ _suction is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ room_id | int }}"
              suction_level: "{{ _suction | int }}"

      - conditions:
          - condition: template
            value_template: "{{ _water is number }}"
        sequence:
          - service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vac }}"
            data:
              segments:
                - "{{ room_id | int }}"
              water_volume: "{{ _water | int }}"

    default:
      - service: dreame_vacuum.vacuum_clean_segment
        target:
          entity_id: "{{ _vac }}"
        data:
          segments:
            - "{{ room_id | int }}"
